version: "3.9"

networks:
  vector:

services:
  #### NODE STACK 1
  node1:
    container_name: node1
    image: connextproject/vector_node:$VECTOR_VERSION
    restart: always
    environment:
      VECTOR_PROD: "true"
      VECTOR_PG_HOST: db-node1
      VECTOR_PG_PORT: 5432
      VECTOR_PG_DATABASE: vector
      VECTOR_PG_USERNAME: vector
      VECTOR_PG_PASSWORD: vector
      VECTOR_MNEMONIC: $MNEMONIC_1
    ports:
      - 8001:8000
    volumes:
      - ./config.json:/app/config.json
    depends_on:
      - db-node1
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - vector
  db-node1:
    container_name: db-node1
    image: connextproject/vector_database:$VECTOR_VERSION
    restart: always
    environment:
      VECTOR_PROD: "true"
      POSTGRES_DB: vector
      POSTGRES_USER: vector
      POSTGRES_PASSWORD: vector
    volumes:
      - database_node1:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - vector
  #### END NODE STACK 2

  #### NODE STACK 2
  node2:
    container_name: node2
    image: connextproject/vector_node:$VECTOR_VERSION
    restart: always
    environment:
      VECTOR_PROD: "true"
      VECTOR_PG_HOST: db-node2
      VECTOR_PG_PORT: 5432
      VECTOR_PG_DATABASE: vector
      VECTOR_PG_USERNAME: vector
      VECTOR_PG_PASSWORD: vector
      VECTOR_MNEMONIC: $MNEMONIC_2
    ports:
      - 8002:8000
    volumes:
      - ./config.json:/app/config.json
    depends_on:
      - db-node2
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - vector
  db-node2:
    container_name: db-node2
    image: connextproject/vector_database:$VECTOR_VERSION
    restart: always
    environment:
      VECTOR_PROD: "true"
      POSTGRES_DB: vector
      POSTGRES_USER: vector
      POSTGRES_PASSWORD: vector
    volumes:
      - database_node2:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - vector
  #### END NODE STACK 2

volumes:
  database_node1:
  database_node2:
